AWSTemplateFormatVersion: 2010-09-09
Description: This template will create a role giving Watching That read-only access to your FreeWheel logs and reports
Parameters:
  FWNetworkId:
    Type: String
    Description: Enter your FreeWheel Network ID
  WTAccountId:
    Type: String
    Default: 409092538980
    Description: Enter the Watching That AWS account ID if provided or leave unchanged otherwise
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "WatchingthatProxyRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Resource: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref WTAccountId
                - ':root'
      Policies:
        # Inline policy
        - PolicyName: "AllowFWAssumeRole"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "sts:AssumeRole"
                Resource: !Join
                  - ''
                  - - 'arn:aws:iam::265086463190:role/'
                    - !Ref FWNetworkId
                    - '-V4LogAccess-role'
              - Effect: Allow
                Action: "sts:AssumeRole"
                Resource: !Join
                  - ''
                  - - 'arn:aws:iam::697717316240:role/'
                    - !Ref FWNetworkId
                    - '-ReportAccess-role'
